# Data Load & Basic Cleaning
- Data load
- Data understanding
- Data Exploration
- Basic Cleaning
- save Clean data

In [1]:
#imports
import numpy as np
import pandas as pd

In [2]:
# load Data
data = pd.read_csv(r"D:\ML_Project\Customer_churn_predection\Data\Telco_Customer_Churn.csv")
data.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,NaN,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,NaN,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,NaN,53.85,NaN,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,NaN,42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,NaN,70.70,151.65,Yes

In [3]:
# Backup data and info
df = data.copy()
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7053 entries, 0 to 7052
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7053 non-null   str
 1   gender            7053 non-null   str
 2   SeniorCitizen     7053 non-null   int64
 3   Partner           7053 non-null   str
 4   Dependents        7053 non-null   str
 5   tenure            7053 non-null   int64
 6   PhoneService      7053 non-null   str
 7   MultipleLines     7048 non-null   str
 8   InternetService   7050 non-null   str
 9   OnlineSecurity    7053 non-null   str
 10  OnlineBackup      7053 non-null   str
 11  DeviceProtection  7053 non-null   str
 12  TechSupport       7053 non-null   str
 13  StreamingTV       7053 non-null   str
 14  StreamingMovies   7053 non-null   str
 15  Contract          7053 non-null   str
 16  PaperlessBilling  7053 non-null   str
 17  PaymentMethod     7050 non-null   str
 18  MonthlyCharges    7049 non-null   float64
 19  TotalCharges      7050 non-null   str
 20  Churn             7048 non-null   str
dtypes: float64(1), int64(2), str(18)
memory usage: 1.9 MB

In [4]:
# Meta-Data
print("No. of rows:", df.shape[0])
print("No. of Columns:", df.shape[1])
all_Columns = df.columns.to_list()
num_Columns = df.select_dtypes(include = "number").columns.to_list()
cat_Columns = df.select_dtypes(include = "object").columns.to_list()

print("All Columns: \n", all_Columns)
print("\nNumeric Columns: \n", num_Columns)
print("\nCategorical Columns: \n", cat_Columns)

print("\nData Types: \n", df.dtypes)

No. of rows: 7053
No. of Columns: 21
All Columns:
 ['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn']

Numeric Columns:
 ['SeniorCitizen', 'tenure', 'MonthlyCharges']

Categorical Columns:
 ['customerID', 'gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod', 'TotalCharges', 'Churn']

Data Types:
 customerID              str
gender                  str
SeniorCitizen         int64
Partner                 str
Dependents              str
tenure                int64
PhoneService            str
MultipleLines           str
InternetService         str
OnlineSecurity          str
OnlineBackup            str
DeviceProtection        str
TechSupport             str
StreamingTV             str
StreamingMovies         str
Contract                str
PaperlessBilling        str
PaymentMethod           str
MonthlyCharges      float64
TotalCharges            str
Churn                   str
dtype: object

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_29544\3494705380.py:6: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_Columns = df.select_dtypes(include = "object").columns.to_list()

In [5]:
# Duplicate
print("Duplicated count: - ", df.duplicated().sum())
print("Duplicate Rows")
df[df.duplicated()]

Duplicated count: -  10
Duplicate Rows

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
7043,4183-MYFRB,Female,0,No,No,21,Yes,No,Fiber optic,No,...,Yes,No,No,Yes,Month-to-month,Yes,Electronic check,90.05,1862.9,No
7044,8779-QRDMV,Male,1,No,No,1,No,No phone service,DSL,No,...,Yes,No,No,Yes,Month-to-month,Yes,Electronic check,39.65,39.65,Yes
7045,1680-VDCWW,Male,0,Yes,No,12,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,One year,No,Bank transfer (automatic),19.80,202.25,No
7046,1066-JKSGK,Male,0,No,No,1,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Month-to-month,No,Mailed check,20.15,20.15,Yes
7047,3638-WEABW,Female,0,Yes,No,58,Yes,Yes,DSL,No,...,No,Yes,No,No,Two year,Yes,Credit card (automatic),59.90,3505.1,No
7048,6322-HRPFA,Male,0,Yes,Yes,49,Yes,No,DSL,Yes,...,No,Yes,No,No,Month-to-month,No,Credit card (automatic),59.60,2970.3,No
7049,6865-JZNKO,Female,0,No,No,30,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Bank transfer (automatic),55.30,1530.6,No
7050,6467-CHFZW,Male,0,Yes,Yes,47,Yes,Yes,Fiber optic,No,...,No,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.35,4749.15,Yes
7051,8665-UTDHZ,Male,0,Yes,Yes,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,No,Electronic check,30.20,30.2,Yes
7052,5248-YGIJN,Male,0,Yes,No,72,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Credit card (automatic),90.25,6369.45,No

In [6]:
#Drop duplicates
df.drop_duplicates()
print("Duplicated count after deleation", df.duplicated().sum())

Duplicated count after deleation 10

In [7]:
# Remove irrelevant column "customerID"
df.drop(columns = "customerID", inplace = True)
df.head(2)

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,NaN,No
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,NaN,No

In [8]:
# Change Data-Type of "TotalCharges"
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors = 'coerce')
df.dtypes

gender                  str
SeniorCitizen         int64
Partner                 str
Dependents              str
tenure                int64
PhoneService            str
MultipleLines           str
InternetService         str
OnlineSecurity          str
OnlineBackup            str
DeviceProtection        str
TechSupport             str
StreamingTV             str
StreamingMovies         str
Contract                str
PaperlessBilling        str
PaymentMethod           str
MonthlyCharges      float64
TotalCharges        float64
Churn                   str
dtype: object

In [9]:
# Save clean Data
clean_data_path = r"D:\ML_Project\Customer_churn_predection\Data\cleaned_data.csv"
df.to_csv(clean_data_path, index = False)
print("Cleaned data is save as cleaned_data in D:\ML_Project\Customer_churn_predection\Data")

Cleaned data is save as cleaned_data in D:\ML_Project\Customer_churn_predection\Data

<>:4: SyntaxWarning: "\M" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\M"? A raw string is also an option.
<>:4: SyntaxWarning: "\M" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\M"? A raw string is also an option.
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_29544\1728748502.py:4: SyntaxWarning: "\M" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\M"? A raw string is also an option.
  print("Cleaned data is save as cleaned_data in D:\ML_Project\Customer_churn_predection\Data")